{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8bd6c12a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import psycopg2 as pg\n",
    "from psycopg2 import sql\n",
    "from sqlalchemy import create_engine\n",
    "import io"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "45ec4e9a",
   "metadata": {},
   "outputs": [],
   "source": [
    "engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/comercio_exterior')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8e8773c6",
   "metadata": {},
   "outputs": [],
   "source": [
    "pasta_importacao = '/home/edcarlos/Data-Analytics-Comercio-Exterior/datalake/gold/agreg_importacao'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "33d13e93",
   "metadata": {},
   "outputs": [],
   "source": [
    "arquivos_csv = [f for f in os.listdir(pasta_importacao) if f.endswith('.csv')]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a08dac9a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enviando dist_pais_ano_vl_fob.csv para a tabela 'dist_pais_ano_vl_fob'...\n",
      " Erro ao enviar dist_pais_ano_vl_fob para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Enviando evol_temp_imp.csv para a tabela 'evol_temp_imp'...\n",
      " Erro ao enviar evol_temp_imp para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Enviando top_10_produtos.csv para a tabela 'top_10_produtos'...\n",
      " Erro ao enviar top_10_produtos para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Enviando top_10_paises_imp.csv para a tabela 'top_10_paises_imp'...\n",
      " Erro ao enviar top_10_paises_imp para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Enviando media_frete_seguro.csv para a tabela 'media_frete_seguro'...\n",
      " Erro ao enviar media_frete_seguro para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Todos os arquivos foram enviados para o banco com sucesso.\n"
     ]
    }
   ],
   "source": [
    "for arquivo in arquivos_csv:\n",
    "    caminho_completo = os.path.join(pasta_importacao, arquivo)\n",
    "    nome_tabela = os.path.splitext(arquivo)[0]\n",
    "\n",
    "    print(f\"Enviando {arquivo} para a tabela '{nome_tabela}'...\")\n",
    "\n",
    "    try:\n",
    "        with open(caminho_completo, 'rb') as f:\n",
    "            content = f.read()\n",
    "\n",
    "        # Decodifica substituindo caracteres inválidos\n",
    "        decoded_content = content.decode('latin1', errors='replace')\n",
    "\n",
    "        # Converte string limpa para \"arquivo virtual\" e lê com pandas\n",
    "        df = pd.read_csv(io.StringIO(decoded_content))\n",
    "    except Exception as e:\n",
    "        print(f\" Erro ao ler {arquivo}: {e}\")\n",
    "        continue\n",
    "\n",
    "    # Envia para o banco\n",
    "    try:\n",
    "        df.to_sql(name=nome_tabela, con=engine,  schema='importacao', if_exists='replace', index=False)\n",
    "        print(f\" {nome_tabela} enviada com sucesso.\")\n",
    "    except Exception as e:\n",
    "        print(f\" Erro ao enviar {nome_tabela} para o banco: {e}\")\n",
    "\n",
    "print(\"Todos os arquivos foram enviados para o banco com sucesso.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
